server:
  port: ${PORT:8080}
  error:
    include-message: always

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: users-db
  mail:
    host: smtp.gmail.com
    port: 587
    username: info.unihive@gmail.com
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${API_SECRET_KEY}
