server:
    port: 8080
    error:
        include-message: always

spring:
    application:
        name: user-service
    # data:
    #     mongodb:
    #         uri: mongodb+srv://ilyasskrichi:${DB_PASSWORD}@etawsilcluster.o74px.mongodb.net/?retryWrites=true&w=majority&appName=eTawsilCluster
    #         database: users-db
    mail:
        host: smtp.gmail.com
        port: 587
        username: info.unihive@gmail.com
        password: ${PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

jwt:
    secret: SDmcs5V70Nm78iipxGh01nIbZLvBfOOO3de0RkjTFvQ=
