server:
    port: 8081
    error:
        include-message: always

spring:
    application:
        name: ticket-service
    datasource:
        url: jdbc:postgresql://localhost:5432/tickets-db
        username: postgres
        password: 1234
        driverClassName: org.postgresql.Driver
        hikari:
            data-source-properties:
                prepareThreshold: 0
    jpa:
        hibernate:
            ddl-auto: create
        open-in-view: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
            show-sql: true

stripe:
    secret-key: sk_test_51QMABUDWNHvbLqXJvRxzUzndzmYbNtH1ZHZDPqbznR4YjeKh3FhS2F7VyjWSUSMVOqwmXMQBiyQ4lawmWOrWdr7x00B3cglai7
    public-key: pk_test_51QMABUDWNHvbLqXJe3m9BOu3Do83g4SfF0nGq3oWs2WNkgfW5RtGb6mzxcnPbygRp9HWLOjZ7W156EJ7TbYX2mfx00de2cOkBt
